### ISSUE TITLE
Any number Multiply by zero gives exception

### ISSUE THREAD

**Issue by jaidevnaik5886** [ZieIony/Calc#1]
I tried a multiplication expression (5*0), it gives a divide by zero exception, but it should be zero . Can you fix this issue as i m using it in my project

**Comment by ZieIony** [comment]
I'm happy that my project is useful to you. Thanks for spotting and reporting the bug. I already fixed it and the new version is available on the master. I'm without access to a proper computer right now, so the unit tests and other changes have to wait.
